### ISSUE TITLE
Create "Folder is full" interaction

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#45]

**Comment by nicolasfranck** [comment]
Does that mean that there are restrictions planned on the folder size (number of files, sum of file sizes)?

**Comment by nics** [comment]
@mietcls is there a need for this?

**Comment by mietcls** [comment]
@nics Depends, if we limited it. Do we not limit it?

**Comment by nicolasfranck** [comment]
@mietcls there is no limit at the moment, because the storage in S3 of UGent exceed our expectations (terabytes). Given the fact that files here do not live very long, putting a limit on a folder is unneeded.

@nics But of course if want to offer a "download all" button (see one of my PR's), the size of that folder becomes important. The bigger the folder, the longer the download takes, the more chances there are that something will fail..

**Comment by mietcls** [comment]
This feature is still in refinement, so if we discover we need it for the download all button, it will remain here and will be refined as needed.

**Comment by mietcls** [comment]
Will fix this if problem arises for #48
